CREATE SCHEMA "StoEntries";

CREATE TABLE "StoEntries"."TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS" (
  "SNO" "int IDENTITY(1,1)" NOT NULL,
  "PO_REF_NO" varchar(50),
  "ADDITIONAL_COST_TYPE" varchar(100),
  "AMOUNT" decimal(15,2),
  "REMARKS" varchar(1000),
  "STATUS_MASTER" varchar(50),
  "CREATED_BY" varchar(50),
  "CREATED_DATE" datetime,
  "CREATED_MAC_ADDRESS" varchar(50),
  "MODIFIED_BY" varchar(50),
  "MODIFIED_DATE" datetime,
  "MODIFIED_MAC_ADDRESS" varchar(50),
  PRIMARY KEY ("SNO")
);

CREATE TABLE "StoEntries"."tbl_Purchase_Order_Conversation_Dtl" (
  "Sno" "int IDENTITY(1,1)" NOT NULL,
  "PO_Ref_No" varchar(50),
  "Respond_Person" varchar(50),
  "Discussion_Details" "varchar(MAX)",
  "Response_Status" varchar(50),
  "Status_entry" varchar(50),
  "Remarks" varchar(50),
  "Created_By" varchar(50),
  "Created_Date" datetime,
  "Created_Mac_Address" varchar(50),
  "Modified_By" varchar(50),
  "Modified_Date" datetime,
  "Modified_Mac_Address" varchar(50),
  PRIMARY KEY ("Sno")
);

CREATE TABLE "StoEntries"."tbl_Purchase_Order_Dtl" (
  "Sno" "int IDENTITY(1,1)" NOT NULL,
  "PO_Ref_No" varchar(50),
  "Request_STORE_ID" int,
  "PO_REQUEST_REF_NO" varchar(50),
  "Proforma_Invoice_Ref_No" varchar(50),
  "SECTION_ID" int,
  "MACHINE_ID" int,
  "Main_Category_Id" int,
  "Sub_Category_Id" int,
  "Product_Id" int,
  "Packing_Type" varchar(50),
  "No_Pcs_Per_Packing" decimal(15,2),
  "Total_Pcs" decimal(15,4),
  "Total_Packing" decimal(15,4),
  "Rate_Per_Pcs" decimal(15,6),
  "Product_Amount" decimal(15,2),
  "Discount_Percentage" decimal(15,2),
  "Discount_Amount" decimal(15,2),
  "Total_Product_Amount" decimal(15,4),
  "VAT_Percentage" decimal(15,2),
  "VAT_Amount" decimal(15,4),
  "Final_Product_Amount" decimal(15,4),
  "Remarks" varchar(2000),
  "Status_Entry" varchar(20),
  "Created_By" varchar(50),
  "Created_Date" datetime,
  "Created_Mac_Address" varchar(50),
  "Modified_By" varchar(50),
  "Modified_Date" datetime,
  "Modified_Mac_Address" varchar(50),
  "Alternate_Product_Name" varchar(500),
  "LC_NEEDED_STATUS" varchar(50),
  "LC_APPLY_STATUS" varchar(50),
  "LC_APPLIED_DATE" datetime,
  "LC_NO" varchar(50),
  "SUP_DOC_FILE" "varbinary(MAX)",
  "Truck_ID" int,
  "Response_1_Person" varchar(50),
  "Response_1_Date" datetime,
  "Response_1_Status" varchar(50),
  "Response_1_Remarks" varchar(5000),
  "Response_1_Approved_Total_Packing" decimal(15,2),
  "Response_1_Approved_Total_Pcs" decimal(15,2),
  "Response_2_Person" varchar(50),
  "Response_2_Date" datetime,
  "Response_2_Status" varchar(50),
  "Response_2_Remarks" varchar(5000),
  "Response_2_Approved_Total_Packing" decimal(15,2),
  "Response_2_Approved_Total_Pcs" decimal(15,2),
  "Final_Response_Person" varchar(50),
  "Final_Response_Date" datetime,
  "Final_Response_Status" varchar(50),
  "Final_Response_Remarks" varchar(5000),
  "Final_Response_Approved_Total_Packing" decimal(15,2),
  "Final_Response_Approved_Total_Pcs" decimal(15,2),
  "Trailer_id" int,
  PRIMARY KEY ("Sno")
);

CREATE TABLE "StoEntries"."TBL_PURCHASE_ORDER_FILES_UPLOAD" (
  "SNO" "int IDENTITY(1,1)" NOT NULL,
  "PO_REF_NO" varchar(50),
  "DESCRIPTION_DETAILS" varchar(100),
  "FILE_NAME" varchar(150),
  "CONTENT_TYPE" varchar(50),
  "CONTENT_DATA" "varbinary(MAX)",
  "STATUS_MASTER" varchar(20),
  "CREATED_BY" varchar(50),
  "CREATED_DATE" datetime,
  "CREATED_MAC_ADDRESS" varchar(50),
  "MODIFIED_BY" varchar(50),
  "MODIFIED_DATE" datetime,
  "MODIFIED_MAC_ADDRESS" varchar(50),
  "FILE_TYPE" varchar(50),
  PRIMARY KEY ("SNO")
);

CREATE TABLE "StoEntries"."tbl_Purchase_Order_Hdr" (
  "Sno" "int IDENTITY(1,1)" NOT NULL,
  "PO_Ref_No" varchar(50) NOT NULL,
  "PO_Date" datetime,
  "Purchase_Type" varchar(20),
  "Company_Id" int,
  "Supplier_Id" int,
  "PO_Store_Id" int,
  "Remarks" varchar(2000),
  "Status_Entry" varchar(20),
  "Created_By" varchar(50),
  "Created_Date" datetime,
  "Created_Mac_Address" varchar(50),
  "Modified_By" varchar(50),
  "Modified_Date" datetime,
  "Modified_Mac_Address" varchar(50),
  "Payment_Term" varchar(3000),
  "Mode_Of_Payment" nvarchar(25),
  "Currency_Type" nvarchar(25),
  "Suplier_Proforma_Number" varchar(100),
  "Shipment_Mode" varchar(100),
  "Price_Terms" varchar(150),
  "Shipment_Remarks" varchar(2500),
  "Total_Production_Hdr_Amount" decimal(15,2),
  "Total_Additional_Cost_Amount" decimal(15,2),
  "VAT_Hdr_Amount" decimal(15,2),
  "Total_Final_Production_Hdr_Amount" decimal(15,2),
  "Respond_By" varchar(50),
  "Respond_Date" date,
  "Respond_Status" varchar(50),
  "FIRST_SHIPMENT_DATE" datetime,
  "LC_APPLY_TARGET_DATE" datetime,
  "Response_1_Person" varchar(50),
  "Response_1_Date" datetime,
  "Response_1_Status" varchar(50),
  "Response_1_Remarks" varchar(5000),
  "Response_1_Mac_address" varchar(50),
  "Response_2_Person" varchar(50),
  "Response_2_Date" datetime,
  "Response_2_Status" varchar(50),
  "Response_2_Remarks" varchar(5000),
  "Response_2_Mac_address" varchar(50),
  "Final_Response_Person" varchar(50),
  "Final_Response_Date" datetime,
  "Final_Response_Status" varchar(50),
  "Final_Response_Remarks" varchar(5000),
  "Requested_Date" datetime,
  "Requested_By" varchar(50),
  "Requested_Mac_Address" varchar(50),
  "Stock_Company_Transfer_Ref_No" varchar(50),
  "Loading_Port_Id" int,
  "Discharge_Port_Id" int,
  "Shipment_Type" varchar(50),
  "SUPPLIER_COMPANY_ID" int,
  "STOCK_STORE_ID" int,
  "Imports_Response_1_Person" varchar(50),
  "Imports_Response_1_Date" datetime,
  "Imports_Response_1_Status" varchar(50),
  "Imports_Response_1_Remarks" varchar(500),
  "Imports_Response_1_Mac_Address" varchar(50),
  "Company_OnBehalf_of" int,
  "Purchase_Head_Response_Person" varchar(50),
  "Purchase_Head_Response_Date" datetime,
  "Purchase_Head_Response_Status" varchar(50),
  "Purchase_Head_Response_Remarks" varchar(500),
  "Purchase_Head_Response_Mac_Address" varchar(50),
  "ERP_PI_ref_no" varchar(50),
  "Price_For_CNF_FOB" varchar(20),
  PRIMARY KEY ("PO_Ref_No")
);
